spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888

kafka:
  topics:
    customerCreated: customer-created
  groups:
    customerService: customer-service-group