server:
  port: 0

spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888
  webflux:
    base-path: /api/v1

kafka:
  topics:
    customerCreated: customer-created
  groups:
    customerService: customer-service-group