server:
  port: 0

spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/